# Generated by Django 3.0.7 on 2022-08-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220819_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
